### ISSUE TITLE
Service "inactive (dead)", no hostname generated

### ISSUE THREAD

**Issue by Purty8383** [VolkanSah/Multiple-Isolated-Tor-Instances-for-Hidden-Services#1]
This is exactly what I have been searching for but I'm having an issue. When I check the status of the service created it is "inactive (dead)" and no hidden service hostname has been generated as if the Tor process didn't run properly or with the instance config at least.

I am already running a stand alone Tor process on the server which is still running fine, is this a problem with the latest Tor version or is there something I will need to check to debug on my machine? Thanks.

**Comment by Purty8383** [comment]
Can you send me a contact email please?

**Comment by VolkanSah** [comment]
Sorry do not see it! You must setup your tor instance (onion -domains) before than you can set it up...
